apiVersion: v1
kind: Service
metadata:
name: {{ include "devops-demo.fullname" . }}-svc
spec:
type: {{ .Values.service.type }}
selector:
app: {{ include "devops-demo.name" . }}
ports:
- protocol: TCP
port: {{ .Values.service.port }}
targetPort: 3000
